### ISSUE TITLE
Feature request - SSH start flutter application & Vertical monitor

### ISSUE THREAD

**Issue by kekko7072** [Snapp-Embedded/snapp_installer#1]
Hi @payam-zahedi at first compliments for the great tool, very useful!

I'm planning on using this tool in production for an embedded kiosk device, but i would need to do this two things:
- launch the app using remote ssh (now it's returning error: `(app:2438): Gtk-WARNING **: 10:24:49.602: cannot open display`)
- Launch app full screen in monitor at 90°

Thank you so much !

**Comment by payam-zahedi** [comment]
Hey @kekko7072 Thanks for your support

It seems that you don't want to use `kiosk` command, and you want to do it manually.

* Your first issue is related to the ssh connection. In SSH connection, we don't have a default defined `$DISPLAY`.

So you can put your default display in the beginning of your command. For example: 

```bash
DISPLAY=:0 flutter run
```

* And for your second issue I guess you can use `SystemChrome.setPreferredOrientations` in flutter. Check out this answer on stackoverflow

https://stackoverflow.com/a/52365208/9689717

**Comment by payam-zahedi** [comment]
@kekko7072 

We rebranded this product, so maybe you need to install it again.

**Comment by kekko7072** [comment]
Ok thank you for advices.
