### ISSUE TITLE
Error: Unable to 'pub upgrade' flutter tool.

### ISSUE THREAD

**Issue by RootKid87** [Snapp-Embedded/snapp_installer#9]
Hi, I'm trying to install flutter via snapp_installer install and get the following error

*****************************************
********* Check Flutter Channel *********
*****************************************
Checking Flutter channel

Downloading Linux arm64 Dart SDK from Flutter engine c4cd48e186460b32d44585ce3c103271ab676355...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  212M  100  212M    0     0  5483k      0  0:00:39  0:00:39 --:--:-- 6186k
Building flutter tool...
/home/aka/sdk/flutter/bin/internal/shared.sh: line 23: /home/aka/sdk/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
/home/aka/sdk/flutter/bin/internal/shared.sh: line 23: /home/aka/sdk/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
/home/aka/sdk/flutter/bin/internal/shared.sh: line 23: /home/aka/sdk/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
/home/aka/sdk/flutter/bin/internal/shared.sh: line 23: /home/aka/sdk/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found

Flutter Doctor:

*****************************************
************ Doctor summary: ************
*****************************************

Installation:

 ✓ | Linux Dependency packages | curl git unzip ...
    * ✓ curl is installed
    * ✓ git is installed
    * ✓ unzip is installed
    * ✓ xz-utils is installed
    * ✓ zip is installed
    * ✓ libglu1-mesa is installed
 ✓ | Flutter folder is located in /home/aka/sdk/flutter.
 Flutter command not found globally. Checking common directories...
Flutter installation found at: /home/aka/sdk/flutter/bin/flutter
✓ | Flutter command is available in the PATH.
 ✓ | Flutter command is defined in .bashrc file.
 ✓ | Linux development packages | clang cmake ninja-build ...
    * ✓ clang is installed
    * ✓ cmake is installed
    * ✓ ninja-build is installed
    * ✓ pkg-config is installed
    * ✓ libgtk-3-dev is installed
    * ✓ liblzma-dev is installed

Kiosk Mode: unknown

 ✘ | Auto login is enabled in your device
 ✘ | Kiosk mode is enabled
 ✘ | Kiosk mode packages | xset xdotool ...
    * ✘ x11-xserver-utils is missing
    * ✘ xdotool is missing
    
System info:

RPI:
Raspberry PI 4B 8GB
Raspian 32Bit Headless

Host:
Windows 11
Flutter Version: 3.19.6

Let me know if you need more informations.

kind regards

**Comment by joaoparis** [comment]
Hi there, same problem here, how did you fix it?

**Comment by RootKid87** [comment]
> Hi there, same problem here, how did you fix it? @RootKid87 

@joaoparis You need to check the flutter version on your machine and your PI. If you your machine and PI have different flutter version try to upgrade with command: flutter upgrade

**Comment by joaoparis** [comment]
> > Hi there, same problem here, how did you fix it? @RootKid87
> 
> @joaoparis You need to check the flutter version on your machine and your PI. If you your machine and PI have different flutter version try to upgrade with command: flutter upgrade

thanks for the tip, but I'm still stuck. when running "snapp_installer install" this is my output:
```Flutter command not found globally. Checking common directories...
No Flutter installations found.
Flutter command not found globally. Checking common directories...
No Flutter installations found.
******************************************
********** Installation Summary **********
******************************************


* Get Linux dependencies to be able to run the flutter: curl, git ,...
* Clone the flutter from Github: https://github.com/flutter/flutter
* move flutter to the /home/pi/sdk/flutter directory
* update the path to make the flutter command excutable
* Check and show the flutter path
* add dependencies for developing on linux
* check the flutter channel
* run flutter doctor
* run flutter precache command for linux



Version option not specified.
Installing the latest version of Flutter on the stable channel.


******************************************
******* Flutter Linux Dependencies *******
******************************************
Linux dependencies are already installed
    * ✓ curl is installed
    * ✓ git is installed
    * ✓ unzip is installed
    * ✓ xz-utils is installed
    * ✓ zip is installed
    * ✓ libglu1-mesa is installed

*****************************************
************* Clone Flutter *************
*****************************************
Clone the stable branch of the Flutter repository from GitHub

Cloning into 'flutter'...
remote: Enumerating objects: 521754, done.
remote: Counting objects: 100% (796/796), done.
remote: Compressing objects: 100% (553/553), done.
remote: Total 521754 (delta 434), reused 452 (delta 222), pack-reused 520958
Receiving objects: 100% (521754/521754), 135.83 MiB | 14.66 MiB/s, done.
Resolving deltas: 100% (408533/408533), done.
Updating files: 100% (8283/8283), done.
Flutter cloned successfully.
Flutter moved to the /home/pi/sdk directory

*****************************************
********** Add Flutter to PATH **********
*****************************************
adding flutter to PATH as env in ~/.bashrc.

******************************************
*********** Check Flutter Path ***********
******************************************

Flutter is located at:
/home/pi/sdk/flutter/bin/flutter

******************************************
***** Linux Development Dependencies *****
******************************************
Linux development dependencies are already installed
    * ✓ clang is installed
    * ✓ cmake is installed
    * ✓ ninja-build is installed
    * ✓ pkg-config is installed
    * ✓ libgtk-3-dev is installed
    * ✓ liblzma-dev is installed

*****************************************
********* Check Flutter Channel *********
*****************************************
Checking Flutter channel

Downloading Linux arm64 Dart SDK from Flutter engine edd8546116457bdf1c5bdfb13ecb9463d2bb5ed4...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  220M  100  220M    0     0  31.0M      0  0:00:07  0:00:07 --:--:-- 37.5M
Building flutter tool...
/home/pi/sdk/flutter/bin/internal/shared.sh: line 23: /home/pi/sdk/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
/home/pi/sdk/flutter/bin/internal/shared.sh: line 23: /home/pi/sdk/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory```

**Comment by RootKid87** [comment]
@joaoparis try to delete the sdk folder sudo rm -r sdk. And retry to install by running sudo snapp_installer install

**Comment by joaoparis** [comment]
@RootKid87 thanks for the suggestion. I partially did what you suggested, aside from "sudo snapp_installer install", that retruned: "sudo: snapp_installer: command not found" (that's normal right?)
I ran it without being the super user, and still got the same result.

Moreover, I noticed #10 was adding flutter_pi to the script. I used to have flutter_pi installed on this PI, which was what I was using to run my Flutter App on this machine. Could it be that some configuration is still there and it's causing the issue? I have removed flutter_pi the best way I know how: rm the folder and removing it from the PATH.

**Comment by RootKid87** [comment]
@joaoparis Ok, unfortunately I don't know how your config looks like. You have a 64Bit raspian on your PI?

**Comment by joaoparis** [comment]
@RootKid87  i think this is what your are asking:
![image](https://github.com/user-attachments/assets/befd942a-5fee-42d7-b798-11bac85af7c1)

**Comment by joaoparis** [comment]
I don't have access to the PI physically right now :( but I'll try to do that on Monday

**Comment by RootKid87** [comment]
Let me know if it worked. Have a nice weekend.

**Comment by joaoparis** [comment]
Will do! Meanwhile, I'm going to ping @payam-zahedi maybe he can help ;)

Have a good weekend!!

**Comment by payam-zahedi** [comment]
Hey @joaoparis 

I'm not sure about your need in here? 

What exactly is your problem?

you want to install flutter on raspberry? Or you want to install flutter-pi?

**Comment by payam-zahedi** [comment]
If you want to have a specific version of flutter, just use this command.

``` 
snapp_installer install -v 3.22.0 -f
```
